name: recycle
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  image_gallery_saver: ^2.0.3
  get: ^4.6.6
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  image_picker: ^1.0.7
  flutter_secure_storage: ^9.0.0
  firebase_storage: ^11.6.0
  intl: ^0.19.0

  firebase_core: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
